### ISSUE TITLE
Publish as an NPM package?

### ISSUE THREAD

**Issue by ssorallen** [loicpennequin/convex-vue#1]
Thank you for open sourcing your work!

Would you be willing to publish the library part of this to NPM? I'd be happy to send some PRs to get the build + publish piece together.

**Comment by Darialyphia** [comment]
Hey, thanks for reaching out !

Making this a library was my initial plan, I was keeping it as a template while I was iterating on the library.
I've already did some work by separating the example part (in `/playground`) from the library part (in `/src`). So technically it's ready to be published, just need to setup the publish pipeline, for which I admittedly have little to no experience on, so help is welcome !

There are still a few kinks to iron out when it comes to the remix-style route loaders, since it's a little bit experimental, but otherwise the lib should be good to go.

**Comment by prpanto** [comment]
Any news about this project?

**Comment by ssorallen** [comment]
Looks like @loicpennequin published the project at [`@convex-use/core`](https://www.npmjs.com/package/@convex-vue/core) on NPM. Are there any tasks I can help with, @loicpennequin? Anything you want to get done before calling it v1.0.0?
